/* The static walkthrough's stand-in for the model.
 *
 * This copy of the viewer ships without the simulator.  traces.js (loaded
 * before this file, GENERATED by tools/bundle_traces.mjs) holds the trace of
 * every lesson in lessons.js on its machine, and on its contrast machine;
 * this file answers the two calls viewer.js makes — OOO.paramsPayload() and
 * OOO.simulate() — out of that recording.  A machine that was not recorded
 * cannot be run: there is nothing here to run it with.
 *
 * OOO.recorded tells viewer.js to leave the machine panel out.
 *
 * Plain script, no DOM: defines window.OOO in a page and module.exports
 * under require() (the bundler uses runKey, so there is one copy of it). */

(function (root) {
'use strict';

/** The name a run is filed under: the program and the machine, as the knobs
 *  that differ from the defaults, in sorted order. */
function runKey(program, params, defaults) {
  const patch = {};
  for (const k of Object.keys(params || {}).sort()) {
    if (params[k] !== defaults[k]) patch[k] = params[k];
  }
  return `${program} ${JSON.stringify(patch)}`;
}

const copy = (v) => JSON.parse(JSON.stringify(v));

function paramsPayload() {
  const T = root.TRACES;
  return copy({ schema_version: T.schema_version, params: T.params, defaults: T.defaults,
                units: T.units, limits: T.limits, programs: T.programs });
}

/** `[status, body]`, as the model's simulate(): the recorded trace, or 400. */
function simulate(payload) {
  const T = root.TRACES;
  const hit = T.programs.find((p) => p.text === (payload && payload.program));
  const run = hit && T.runs[runKey(hit.name, (payload && payload.params) || {}, T.defaults)];
  if (!run) return [400, { error: 'machine: this walkthrough has only the recorded examples; this program on this machine is not one of them' }];
  return [200, copy(run)];
}

const OOO = { recorded: true, runKey, paramsPayload, simulate };
if (root.TRACES && typeof root.TRACES === 'object') root.OOO = OOO;
if (typeof module !== 'undefined' && module.exports) module.exports = OOO;
})(typeof window !== 'undefined' ? window : globalThis);
